### ISSUE TITLE
Migrate remaining subdivision holidays to their own methods

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1130]
As per https://github.com/dr-prodigy/python-holidays/pull/1057 and https://github.com/dr-prodigy/python-holidays/pull/1097/ (just another example).

**Comment by KJhellico** [comment]
I plan to migrate New Zealand in a few days.

**Comment by PPsyrius** [comment]
Did we forget to close this issue down by any chance?

**Comment by arkid15r** [comment]
It may be. Thank you @PPsyrius 
I believe it's not that important at this point. Let's revisit this after `v1` is released.
