### ISSUE TITLE
Add Bahamas holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1152]
Useful links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_the_Bahamas
  - https://www.timeanddate.com/holidays/bahamas/

**Comment by PPsyrius** [comment]
Ironically enough, none of the government site got usable data except for https://www.bahamashclondon.net/consular-information/public-holidays/, but that was for 2020.

With some random resort got better formatted sources (but still only on par to Wikipedia): https://tainobeach.com/amenities/grand-bahama-island/holidays/
