### ISSUE TITLE
Add Barbados holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1153]
Useful links:
  -  https://en.wikipedia.org/wiki/Public_holidays_in_Barbados
  - https://www.timeanddate.com/holidays/barbados/

**Comment by arjunanan6** [comment]
Assign to me please, I'd like to help out.  Possibly even with more.

**Comment by arkid15r** [comment]
@arjunanan6 you got it.

Thank you!

**Comment by arjunanan6** [comment]
@arkid15r Pretty much done here, but I can't commit.. I get a lot of errors relating to the pre-checks:

```
[INFO] Stashing unstaged files to /Users/arjun/.cache/pre-commit/patch1689880665-42063.
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing tests/countries/test_barbados.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted holidays/countries/barbados.py

All done! ✨ 🍰 ✨
1 file reformatted, 1 file left unchanged.

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

holidays/countries/barbados.py:66:100: E501 line too long (110 > 99 characters)

isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /Users/arjun/Documents/git/python-holidays/holidays/countries/barbados.py

mypy.....................................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rstcheck.............................................(no files to check)Skipped
tox-ini-fmt..........................................(no files to check)Skipped
setup-cfg-fmt........................................(no files to check)Skipped
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
```

Any idea what's happening here? I believe I set up everything according to the contributor's guide.

**Comment by arjunanan6** [comment]
Issue is with: `make l10n`

**Comment by KJhellico** [comment]
@arjunanan6 try to run `make pre-commit`, this should fix these errors.

**Comment by arjunanan6** [comment]
@KJhellico Thanks. `make pre-commit` goes through without a hitch, but when I push my changes it once again fails at "run tests":

```
run tests................................................................Failed
- hook id: tests
- exit code: 2

make l10n
make[1]: Entering directory 'C:/Users/arjun/Documents/git/python-holidays'
scripts/l10n/generate_po_files.py >/dev/null 2>&1
make[1]: *** [Makefile:27: l10n] Error 1
make[1]: Leaving directory 'C:/Users/arjun/Documents/git/python-holidays'
make: *** [Makefile:15: check] Error 2
```

**Comment by arkid15r** [comment]
The pre-commit runs `make check` (includes `make l10n`, `make pre-commit`, `make doc`, and `make test`) command via `pre-commit/pre-push` hooks.

It seems the problem is w/ `scripts/l10n/generate_po_files.py`. Its output is suppressed when running via `make l10n`
Could you run `scripts/l10n/generate_po_files.py` directly for (hopefully) more descriptive error message?

A link to your exported code branch could also help to troubleshoot it.

My guess is that .po files have some unresolved conflicts (or malformated in some other way).

**Comment by arjunanan6** [comment]
> A link to your exported code branch could also help to troubleshoot it. 

I can't commit as it stands, so can't even get the branch pushed. :( 

I just ran `scripts/l10n/generate_po_files.py` and this is the output: 

`Traceback (most recent call last):
  File "C:\Users\arjun\Documents\git\python-holidays\scripts\l10n\generate_po_files.py", line 111, in <module>
    POGenerator.run()
  File "C:\Users\arjun\Documents\git\python-holidays\scripts\l10n\generate_po_files.py", line 107, in run
    POGenerator().process_countries()
  File "C:\Users\arjun\Documents\git\python-holidays\scripts\l10n\generate_po_files.py", line 73, in process_countries
    create_pot_file(
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\lingua\extract.py", line 426, in main
    for message in extractor(real_filename, extractor_options):
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\lingua\extractors\python.py", line 415, in __call__
    return parser(token_stream, options, filename, lineno)
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\lingua\extractors\python.py", line 187, in __call__
    for (token_type, token, location, _) in token_stream:
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\lingua\extractors\python.py", line 162, in next
    token = self._transform(next(self.queue))
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 452, in _tokenize
    line = readline()
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\site-packages\lingua\extractors\python.py", line 122, in __call__
    line = self.readline()
  File "C:\Users\arjun\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2954: character maps to <undefined>`

**Comment by arjunanan6** [comment]
I've tried this out on my win. machine by the way, on my mac it gives me all the errors from my first comment. I tried out the same files on win. where it reports just this issue with l10n.

**Comment by KJhellico** [comment]
On Windows, localization process is currently problematic. If you want to try this on Win, to solve encoding problem, you need to set environment variable:
```bash
set PYTHONUTF8=1
```
(and better to delete holidays\locale\pot\*.* files, if any exist). So it's easier to try it on Mac, if you can.

> on my mac it gives me all the errors from my first comment

It's pre-commit hook output. These errors were fixed by `make pre-commit`. Now try to run `scripts/l10n/generate_po_files.py` there, on Mac. What will it show?

**Comment by arjunanan6** [comment]
I ran `scripts/l10n/generate_po_files.py` now on my mac and it outputs:
```
No changes found - not replacing holidays/locale/pot/AM.pot
No changes found - not replacing holidays/locale/pot/AR.pot
No changes found - not replacing holidays/locale/pot/AW.pot
No changes found - not replacing holidays/locale/pot/BA.pot
No translatable strings found, aborting
```

**Comment by arjunanan6** [comment]
And this is the output of make pre-commit from the mac:

```
pre-commit run --all-files
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

scripts/generate_release_notes.py:82: error: Module has no attribute "BooleanOptionalAction"  [attr-defined]
Found 1 error in 1 file (checked 314 source files)

rst ``code`` is two backticks............................................Passed
rstcheck.................................................................Passed
tox-ini-fmt..............................................................Passed
setup-cfg-fmt............................................................Passed
make: *** [pre-commit] Error 1
```

**Comment by KJhellico** [comment]
> I ran `scripts/l10n/generate_po_files.py` now on my mac and it outputs:

Try to delete `holidays/locale/pot/*.pot` files first.

> scripts/generate_release_notes.py:82: error: Module has no attribute "BooleanOptionalAction"  [attr-defined]

What's your Python version? This argparse option was added in 3.9. @arkid15r , looks like we have a bit of an inconsistency here 🙄

**Comment by arjunanan6** [comment]
Deleted *.pot files as suggested, but I am not really seeing a difference. My python version is `3.8.5`.

**Comment by arjunanan6** [comment]
Do you think upgrading to 3.9 will help? I have no problems doing that.

**Comment by KJhellico** [comment]
Yes, try with 3.9 minimum.

**Comment by arkid15r** [comment]
> > scripts/generate_release_notes.py:82: error: Module has no attribute "BooleanOptionalAction"  [attr-defined]
> What's your Python version? This argparse option was added in 3.9. @arkid15r , looks like we have a bit of an inconsistency here 🙄

Yeah, I guess `# type: ignore[attr-defined]` should be added to L82. It's not a big deal as the script is for internal purposes, but you're right, we should address that.

@arjunanan6 either that or upgrade to python 3.9 should help.

**Comment by arjunanan6** [comment]
So I am now using python 3.11.1 and have set up a new venv and ran make setup.

Following that, I ran make pre-commit which outputs:
```
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks............................................Passed
rstcheck.................................................................Passed
tox-ini-fmt..............................................................Passed
setup-cfg-fmt............................................................Passed
```

However, if I were to commit something after that, it is back to the same situation as before:
```
% git commit -m "Add Barbados holidays"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/arjun/.cache/pre-commit/patch1690020648-79795.
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing tests/countries/test_barbados.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted holidays/countries/barbados.py

All done! ✨ 🍰 ✨
1 file reformatted, 1 file left unchanged.

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

holidays/countries/barbados.py:66:100: E501 line too long (110 > 99 characters)

isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /Users/arjun/Documents/git/python-holidays/holidays/countries/barbados.py

mypy.....................................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rstcheck.............................................(no files to check)Skipped
tox-ini-fmt..........................................(no files to check)Skipped
setup-cfg-fmt........................................(no files to check)Skipped
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
```

I'm at a loss :/

**Comment by KJhellico** [comment]
```
> [WARNING] Unstaged files detected.
> [INFO] Stashing unstaged files to /Users/arjun/.cache/pre-commit/patch1690020648-79795.
```
Maybe you have unstaged changes made by `pre-commit`? Try to look with `git status` and add them with `git add` if necessary.

**Comment by arjunanan6** [comment]
Oh damn, that was it. Such a silly mistake! I can now run commit, however, when I push..:

```
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rstcheck.............................................(no files to check)Skipped
tox-ini-fmt..........................................(no files to check)Skipped
setup-cfg-fmt........................................(no files to check)Skipped
run tests................................................................Failed
- hook id: tests
- exit code: 2

make l10n
scripts/l10n/generate_po_files.py >/dev/null 2>&1
make[1]: *** [l10n] Error 2
make: *** [check] Error 2

error: failed to push some refs to 'github.com:arjunanan6/python-holidays.git'
```
I can however run generate_po_files.py on its own without any errors.

**Comment by KJhellico** [comment]
```
> run tests................................................................Failed
> - hook id: tests
> - exit code: 2
```
 Run `make test`, you should see errors.

**Comment by arjunanan6** [comment]
I ran `make test` now, and indeed, I missed out on a doc change. That''s fixed, and `make test` runs without errors now. However, I am still getting an error when pushing:

```
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
rst ``code`` is two backticks............................................Passed
rstcheck.................................................................Passed
tox-ini-fmt..........................................(no files to check)Skipped
setup-cfg-fmt........................................(no files to check)Skipped
run tests................................................................Failed
- hook id: tests
- exit code: 2

make l10n
scripts/l10n/generate_po_files.py >/dev/null 2>&1
make[1]: *** [l10n] Error 2
make: *** [check] Error 2

error: failed to push some refs to 'github.com:arjunanan6/python-holidays.git'
```

Truncated output from `make test`:

`1852 passed in 32.50s`

**Comment by KJhellico** [comment]
`scripts/l10n/generate_po_files.py` executed without errors? And `scripts/l10n/generate_mo_files.py` too?

**Comment by arjunanan6** [comment]
Yes, both of those execute without any errors.

**Comment by arjunanan6** [comment]
As I understand, the issue is with 	`make l10n`. I can run make pre-commit just fine. But if run `make l10n`, I get this:

```
scripts/l10n/generate_po_files.py >/dev/null 2>&1
make: *** [l10n] Error 2
```

And there's no problem executing `scripts/l10n/generate_mo_files.py` or `scripts/l10n/generate_po_files.py`.

**Comment by arjunanan6** [comment]
> Does `make l10` command fail when you run it explicitly?

It does, weirdly. I've looked at the Makefile and figured out what it does, but I can't seem to figure out why the two scripts execute individually, but not when run with `make l10`. 

Anyway, I've pushed the changes with `--no-verify`. Thanks a lot for your support and patience!

**Comment by arjunanan6** [comment]
@arkid15r Sorry, I might need your help again, I've made a PR in the 'right' way, but it looks like it still wants to go to master rather than beta. 

I've forked this repo and cloned my fork, switched to the beta branch and then made my own branch. Should do the trick normally. Or did I miss something?

**Comment by KJhellico** [comment]
I changed the branch to beta :)

**Comment by arjunanan6** [comment]
I suppose this one can be closed now @arkid15r.

**Comment by arkid15r** [comment]
That's right, I'll take care of it.
It hasn't been auto-closed after the merge as beta isn't the default branch (may be revisited soon).

Implemented by @arjunanan6 in https://github.com/vacanza/python-holidays/pull/1393
