### ISSUE TITLE
Add Congo holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1165]
**Not to be confused with the neighboring Democratic Republic of the Congo**

Useful links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_the_Republic_of_the_Congo
  - https://www.timeanddate.com/holidays/republic-of-the-congo/

**Comment by PPsyrius** [comment]
@arkid15r
I cannot find any references on Republic Day before June 9, 2021 edit on the said Wikipedia, - [its main and only source](http://mokili.free.fr/jours_feries.php) doesn't observe the "Republic Day" either.

**Comment by PPsyrius** [comment]
NVM, I think I've found the source now - its observance began in 2010: https://www.finances.gouv.cg/sites/default/files/documents/n%C2%AF18-2010%20du%2027%20novembre%202010.PDF
