### ISSUE TITLE
Add Ghana holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1191]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Ghana
  - https://www.timeanddate.com/holidays/ghana/
  - https://www.mint.gov.gh/statutory-public-holidays/
  - https://www.bog.gov.gh/official-holidays/

**Comment by JerryAgbesi** [comment]
I can pick this up if it's still available

**Comment by arkid15r** [comment]
Hi @JerryAgbesi, assigning this to you

Thank you!

**Comment by arkid15r** [comment]
@JerryAgbesi this has been merged into beta!
Thanks a lot for your contribution and the efforts to address the PR review comments!
