### ISSUE TITLE
Add Haiti holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1199]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Haiti
  - https://www.timeanddate.com/holidays/haiti/

**Comment by PPsyrius** [comment]
Weirdly enough, Haiti's own constitution only listed 5 legal holidays, so we might want to research this a bit more
https://www.constituteproject.org/constitution/Haiti_2012

@arkid15r If you don't mind, I plan to work on this one
