### ISSUE TITLE
Add Iran holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1202]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Iran
  - https://www.timeanddate.com/holidays/iran/

**Comment by xmha97** [comment]
This is a list of Iranian holidays, based on the official document:
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf

Used Google Calendar translation:
https://calendar.google.com/calendar/embed?src=en.ir%23holiday%40group.v.calendar.google.com
https://calendar.google.com/calendar/ical/en.ir%23holiday%40group.v.calendar.google.com/public/basic.ics


| #  | Title                                                     | Day | Month |  Calendar |
|----|-----------------------------------------------------------|:---:|:-----:|:---------:|
| 1  | Revolution Day                                            |  2  |   11  | Gregorian |
| 2  | Oil   Nationalization Day                                 |  3  |   20  | Gregorian |
| 3  | Norooz (Persian New Year)                                 |  3  |   21  | Gregorian |
| 4  | Norooz   Holiday                                          |  3  |   22  | Gregorian |
| 5  | Norooz Holiday                                            |  3  |   23  | Gregorian |
| 6  | Norooz   Holiday                                          |  3  |   24  | Gregorian |
| 7  | Islamic Republic Day                                      |  4  |   1   | Gregorian |
| 8  | Nature   Day                                              |  4  |   2   | Gregorian |
| 9  | Demise of Imam Khomeini                                   |  6  |   4   | Gregorian |
| 10 | Khordad   National Uprising                               |  6  |   5   | Gregorian |
| 11 | Tassoua                                                   |  1  |   9   |  Islamic  |
| 12 | Ashura                                                    |  1  |   10  |  Islamic  |
| 13 | Arbaeen                                                   |  2  |   20  |  Islamic  |
| 14 | Demise   of Prophet Muhammad and Martyrdom of Imam Hassan |  2  |   28  |  Islamic  |
| 15 | Martyrdom of Imam Reza                                    |  2  |   29  |  Islamic  |
| 16 | Martyrdom   of Imam Hasan al-Askari                       |  3  |   8   |  Islamic  |
| 17 | Birthday of Prophet Muhammad and   Imam Sadeq             |  3  |   17  |  Islamic  |
| 18 | Martyrdom   of Hazrat Fatima                              |  6  |   3   |  Islamic  |
| 19 | Birthday of Imam Ali and   Father's Day                   |  7  |   13  |  Islamic  |
| 20 | Prophet's   Ascension                                     |  7  |   27  |  Islamic  |
| 21 | Imam Mahdi's birthday                                     |  8  |   15  |  Islamic  |
| 22 | Martyrdom of Imam Ali                                     |  9  |   21  |  Islamic  |
| 23 | Eid-e-Fetr (End of Ramadan)                               |  10 |   1   |  Islamic  |
| 24 | Eid-e-Fetr   (Additional Holiday)                         |  10 |   2   |  Islamic  |
| 25 | Martyrdom of Imam Sadeq                                   |  10 |   25  |  Islamic  |
| 26 | Eid-e-Ghorban   (Feast of Sacrifice)                      |  12 |   10  |  Islamic  |
| 27 | Eid-e-Ghadir                                              |  12 |   18  |  Islamic  |

**Comment by xmha97** [comment]
Hi @arkid15r
This is a list of Iranian holidays,

Based on the official document:
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf

Used Google Calendar translation:
https://calendar.google.com/calendar/embed?src=en.ir%23holiday%40group.v.calendar.google.com
https://calendar.google.com/calendar/ical/en.ir%23holiday%40group.v.calendar.google.com/public/basic.ics


| #  | Title                                                     | Day | Month |  Calendar |
|----|-----------------------------------------------------------|:---:|:-----:|:---------:|
| 1  | Revolution Day                                            |  2  |   11  | Gregorian |
| 2  | Oil   Nationalization Day                                 |  3  |   20  | Gregorian |
| 3  | Norooz (Persian New Year)                                 |  3  |   21  | Gregorian |
| 4  | Norooz   Holiday                                          |  3  |   22  | Gregorian |
| 5  | Norooz Holiday                                            |  3  |   23  | Gregorian |
| 6  | Norooz   Holiday                                          |  3  |   24  | Gregorian |
| 7  | Islamic Republic Day                                      |  4  |   1   | Gregorian |
| 8  | Nature   Day                                              |  4  |   2   | Gregorian |
| 9  | Demise of Imam Khomeini                                   |  6  |   4   | Gregorian |
| 10 | Khordad   National Uprising                               |  6  |   5   | Gregorian |
| 11 | Tassoua                                                   |  1  |   9   |  Islamic  |
| 12 | Ashura                                                    |  1  |   10  |  Islamic  |
| 13 | Arbaeen                                                   |  2  |   20  |  Islamic  |
| 14 | Demise   of Prophet Muhammad and Martyrdom of Imam Hassan |  2  |   28  |  Islamic  |
| 15 | Martyrdom of Imam Reza                                    |  2  |   29  |  Islamic  |
| 16 | Martyrdom   of Imam Hasan al-Askari                       |  3  |   8   |  Islamic  |
| 17 | Birthday of Prophet Muhammad and   Imam Sadeq             |  3  |   17  |  Islamic  |
| 18 | Martyrdom   of Hazrat Fatima                              |  6  |   3   |  Islamic  |
| 19 | Birthday of Imam Ali and   Father's Day                   |  7  |   13  |  Islamic  |
| 20 | Prophet's   Ascension                                     |  7  |   27  |  Islamic  |
| 21 | Imam Mahdi's birthday                                     |  8  |   15  |  Islamic  |
| 22 | Martyrdom of Imam Ali                                     |  9  |   21  |  Islamic  |
| 23 | Eid-e-Fetr (End of Ramadan)                               |  10 |   1   |  Islamic  |
| 24 | Eid-e-Fetr   (Additional Holiday)                         |  10 |   2   |  Islamic  |
| 25 | Martyrdom of Imam Sadeq                                   |  10 |   25  |  Islamic  |
| 26 | Eid-e-Ghorban   (Feast of Sacrifice)                      |  12 |   10  |  Islamic  |
| 27 | Eid-e-Ghadir                                              |  12 |   18  |  Islamic  |

(Download JSON version: [fa-IR.json](https://github.com/dr-prodigy/python-holidays/files/11584120/fa-IR.json.log))

**Comment by arkid15r** [comment]
Thanks for sharing this @xmha97!

**Comment by xmha97** [comment]
> Thanks for sharing this @xmha97!

@arkid15r You're welcome.
But note that some events in Iran are based on the Gregorian calendar and others are based on the Islamic calendar.

**Comment by xmha97** [comment]
In addition, can I add events of Iran in Persian language (fa-IR)?
I haven't used your library yet and I don't know if it has language capability or not.

**Comment by arkid15r** [comment]
>But note that some events in Iran are based on the Gregorian calendar and others are based on the Islamic calendar.

Yeah, that's fine. We have countries that use [multiple calendars](https://github.com/dr-prodigy/python-holidays/blob/beta/holidays/countries/indonesia.py#L22) for their holidays.

> In addition, can I add events of Iran in Persian language (fa-IR)?
I haven't used your library yet and I don't know if it has language capability or not.

Yes, it's possible to localize holiday names. The original holiday names should (preferably) be in country's official language which I believe `fa_IR` actually is.

**Comment by xmha97** [comment]
> Yes, it's possible to localize holiday names.

This is great. 👍
In what format should I send events? I need a template.
Do you agree with posting a comment on this issue?

**Comment by arkid15r** [comment]
Normally, when a person volunteers to add a new country holidays support it goes straight to the library code of the new country (see #1168 as one of the most recent examples). If a country support has already been implemented the l10n process requires regular .po files like [this one](https://github.com/dr-prodigy/python-holidays/pull/1168/files#diff-4da4c2b405fa31a8db553b3fcca76658afb0cf908cd5c46465a9ab597df27039). You can find some additional info [here](https://github.com/dr-prodigy/python-holidays/blob/master/CONTRIBUTING.rst).

Posting the original holiday names here would of course be appreciated but does not guaranty adding them to the python-holidays until somebody implements the code. 

I hope I interpreted your questions correctly.

**Comment by arkid15r** [comment]
Implemented in #1409
