### ISSUE TITLE
Add Laos holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1215]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Laos
  - https://www.timeanddate.com/holidays/laos/

**Comment by PPsyrius** [comment]
More on this, aside from the official ASEAN calendar for 2022-2023 we used for double-chceking in Brunei and Cambodia's PR:

- There appears to be a Laotian Securities Exchange Official Calendar [here](http://www.lsx.com.la/cal/getHolidayCalendar.do?lang=lo&year=2019&month=01&yearMonth=201901&category=H&num=&yearSelect=2018&monthSelect=12) which from a quick check only works from 2019 only. Interestingly enough the calendar indicates that observance/in-lieu are moved to the next working day if existing holiday fall on the weekends.

- Laotian Keyword search: `ວັນພັກ` on Lao Official Gazette i.e. [2016 Official Calendar](https://laoofficialgazette.gov.la/kcfinder/upload/files/%E0%BA%94%E0%BA%B3%E2%80%8B%E0%BA%A5%E0%BA%B1%E0%BA%94%E0%BA%A7%E0%BB%88%E0%BA%B2%E2%80%8B%E0%BA%94%E0%BB%89%E0%BA%A7%E0%BA%8D%20%E0%BA%A7%E0%BA%B1%E0%BA%99%E2%80%8B%E0%BA%9E%E0%BA%B1%E0%BA%81.pdf)
