### ISSUE TITLE
Add Palau holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1238]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Palau
  - https://www.timeanddate.com/holidays/palau/

**Comment by PPsyrius** [comment]
Additional official sources:
- Actual Law (see Chapter 7: Holidays): http://www.paclii.org/pw/legis/consol_act/gpt1262/
- Family Day added in 20147: https://www.palaugov.pw/wp-content/uploads/2017/11/RPPL-No.-10-15-re.-Family-Day-Holiday.pdf

@arkid15r If you don't mind, I intend to work on this after Seychelles.

**Comment by arkid15r** [comment]
Thank you, @PPsyrius!
