### ISSUE TITLE
Add Papua New Guinea holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1239]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Papua_New_Guinea
  - https://www.timeanddate.com/holidays/papua-new-guinea/

**Comment by PPsyrius** [comment]
I'm working on this at the moment based on [the actual law itself as of 1953](http://www.paclii.org/pg/legis/consol_act/pha1953163.pdf) and [wayback machine copy for actual holiday dates between 2021-2024](https://web.archive.org/web/20201218104840/https://www.businessadvantagepng.com/papua-new-guinea-public-for-holidays/)
