### ISSUE TITLE
Add Saint Kitts and Nevis holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1261]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Saint_Kitts_and_Nevis
  - https://www.timeanddate.com/holidays/saint-kitts-and-nevis/

**Comment by PPsyrius** [comment]
SKN's own [Public Holidays Act](https://lawcommission.gov.kn/wp-content/documents/Revised-Acts-of-St-Kitts-and-Nevis/Revised-Acts-of-St-Kitts-and-Nevis-2009/Ch-23_23-Public-Holidays-Act.pdf) document 
[Ch-23_23-Public-Holidays-Act.pdf](https://github.com/user-attachments/files/17039650/Ch-23_23-Public-Holidays-Act.pdf)

I'm planning to take on this next.
