### ISSUE TITLE
Add Seychelles holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1267]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Seychelles
  - https://www.timeanddate.com/holidays/seychelles/
  - https://www.cbs.sc/PublicHolidays.html

**Comment by PPsyrius** [comment]
I'm working on this one.

**Comment by arkid15r** [comment]
Thanks a lot, @PPsyrius!

**Comment by PPsyrius** [comment]
@arkid15r Would it be possible to use `subdivisions_aliases` to aggregate subdivisions?

i.e. 
```python
subdivisions_aliases = {
  07: "Inner Islands"
  14: "Inner Islands"
  15: "Inner Islands"
  26: "Outer Islands"
}
```

**Comment by arkid15r** [comment]
> @arkid15r Would it be possible to use `subdivisions_aliases` to aggregate subdivisions?
> 
> i.e.
> 
> ```python
> subdivisions_aliases = {
>   07: "Inner Islands"
>   14: "Inner Islands"
>   15: "Inner Islands"
>   26: "Outer Islands"
> }
> ```

Not sure about this one. I checked available subdivisions here -- https://www.iso.org/obp/ui/#iso:code:3166:SC
The aliases would work for mapping names to numeric codes, e,g, `Anse Boileau: "02"`

It sounds like you're looking for some problem solution? Please add context details if you have any.

**Comment by PPsyrius** [comment]
> > @arkid15r Would it be possible to use `subdivisions_aliases` to aggregate subdivisions?
> > i.e.
> > ```python
> > subdivisions_aliases = {
> >   07: "Inner Islands"
> >   14: "Inner Islands"
> >   15: "Inner Islands"
> >   26: "Outer Islands"
> > }
> > ```
> 
> Not sure about this one. I checked available subdivisions here -- https://www.iso.org/obp/ui/#iso:code:3166:SC The aliases would work for mapping names to numeric codes, e,g, `Anse Boileau: "02"`
> 
> It sounds like you're looking for some problem solution? Please add context details if you have any.

From what I understand Seychelles election take 3 days: the first day on Outer Islands, then Inner Islands, and the main island Mahé itself - as these dates has no rigid rules each subdivision need to be coded as `special_public_holidays` discretely. One of these cases `"Inner Islands"` has 3 subdivisions, so I would like to lessen code duplications here if possible.

**Comment by arkid15r** [comment]
> From what I understand Seychelles election take 3 days: the first day on Outer Islands, then Inner Islands, and the main island Mahé itself - as these dates has no rigid rules each subdivision need to be coded as `special_public_holidays` discretely. One of these cases `"Inner Islands"` has 3 subdivisions, so I would like to lessen code duplications here if possible.

Yeah, now I have better understanding of the subject. Unfortunately, subdivisions aliases mapping is on a higher abstraction level. I don't think it'll help you minimize code duplication. Maybe some common method to invoke for each subdivision?
