### ISSUE TITLE
Add Timor-Leste holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1286]
Links:
  - https://en.wikipedia.org/wiki/Culture_of_East_Timor#Public_holidays
  - https://www.timeanddate.com/holidays/timor-leste/
  - http://timor-leste.gov.tl/wp-content/uploads/2022/03/EN_CdI_National-holidays-2.pdf

**Comment by PPsyrius** [comment]
I'm working on this atm, also found the exact law wording for East Timor here: https://www.ilo.org/dyn/natlex/docs/ELECTRONIC/79910/86128/F-358739794/TMP79910.pdf

**Comment by PPsyrius** [comment]
@arkid15r @KJhellico Hi, I got some quick questions here before I create a PR on this after wrapping the translation for this one, should Timor-Leste appear in the holiday registry as `holidays.countries.timorleste` or `holidays.countries.timor_leste` ?

The official country name always includes the hyphen (`Timor-Leste`) i.e. as seen [here](http://timor-leste.gov.tl/?p=26494&lang=en), pretty sure it's the same case for `Guinea-Bissau` (#1195) too, but the python interpreter seems to not take this well:
```bash
E     File "[directory name]\python-holidays\holidays\countries\__init__.py", line 134
E       from .timor-leste import TimorLeste, TL, TLS
E                  ^
E   SyntaxError: invalid syntax
```

Please let me know if you have reached a consensus on this.

**Comment by arkid15r** [comment]
He @PPsyrius,
yeah, you can't do that in Python. 

I'd go with `holidays.countries.timor_leste` for the module name and `TimorLeste` for the class name based on your description.
