### ISSUE TITLE
Add REVISED_JULIAN_CALENDAR

### ISSUE THREAD

**Issue by KJhellico** [vacanza/python-holidays#1378]
Add REVISED_JULIAN_CALENDAR constant for Christian holidays of Eastern Orthodox countries that use [this calendar](https://en.wikipedia.org/wiki/Revised_Julian_calendar) (Bulgaria, Cyprus, Greece, Romania, from Sep 2023 - Ukraine).

**Comment by arkid15r** [comment]
I believe this was resolved by https://github.com/vacanza/python-holidays/pull/1380
