### ISSUE TITLE
Flake8 6.1.0 errors: "`do not compare types`"

### ISSUE THREAD

**Issue by PPsyrius** [vacanza/python-holidays#1408]
Here are some errors as output by the new `Flake8` version as done on `beta` branch:
>flake8...................................................................Failed
>- hook id: flake8
>- exit code: 1
>holidays/helpers.py:20:32: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>holidays/holiday_base.py:525:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>holidays/holiday_base.py:528:14: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>tests/common.py:203:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>tests/common.py:281:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>tests/common.py:338:27: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
>tests/common.py:339:42: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()``

**Comment by arkid15r** [comment]
Hey @PPsyrius, thanks for filing this!

The fix has been merged into beta.
