### ISSUE TITLE
For Canada, Remembrance Day is treated differently depending on subdivisions

### ISSUE THREAD

**Issue by timcashion** [vacanza/python-holidays#1443]
First, thanks for the great package! Very helpful. 

Some Canadian subdivisions use the _add_observed method before adding 'Remembrance Day' as a holiday, whereas others don't use this. The effect is that Remembrance Day falling on a Sunday will have an observed day on the following Monday in 5 subdivisions but not the other 6. I haven't seen anything that these holidays are actually treated differently in this way. 

In addition for those that use the self._add_observed() method, they have `include_sat=False`. I also haven't seen any reference that says this holiday doesn't count for a day in-lieu (i.e., observed) if falling on the Saturday but does if falling on the Sunday. 

`self._add_observed(self._add_remembrance_day(tr("Remembrance Day")), include_sat=False)`
Used by:
NL, NS, NT, PE, SK
_add_subdiv_pe_holidays

`self._add_remembrance_day(tr("Remembrance Day"))`
Used by:
AB, BC, MB, NB, NU, YT

Recommended fixes:
- Change all uses to use self._add_observed() before self._add_remembrance_day() (In Canada)
- Set include_sat=True in all uses of self._add_observed() for Remembrance Day (In Canada)

If you agree with the changes, I can make a PR for this.

**Comment by arkid15r** [comment]
Hi Tim, thanks for filing this. 

Yeah, I can't deny Canada holidays implementation needs some attention (see another recent issue #1439). 
BTW, the issue detailed description is much appreciated 👍 

I took a quick look and it seems those changes were added by @KJhellico (who is really good in figuring out holidays and respective observance rules). I guess it was done based on this source https://en.wikipedia.org/wiki/Public_holidays_in_Canada

>If you agree with the changes, I can make a PR for this.

This would be totally awesome as we always encourage people to submit their contributions. I'd wait for a reply from @KJhellico though to make sure that proposed changes are what we want.

If you have any questions -- just let us know.

**Comment by KJhellico** [comment]
@timcashion, thank you for your feedback! I'll take a closer look at this.

**Comment by KJhellico** [comment]
I started with Alberta. [Official source](https://www.alberta.ca/alberta-general-holidays) says nothing about additional holiday if Remebrance Day falls on weekend. The only holiday to be shifted in Alberta is Canada Day (and only if on Sunday):

> Canada Day is on July 1 every year except when it falls on a Sunday, then it’s on July 2.

**Comment by KJhellico** [comment]
Yes, "Observed" in this project - it's something like "additional day off that appears when holiday falls on non-working day (weekend/Sunday/other holiday etc)". But we are trying to use reliable sources, especially official ones, to determine the rules of this "Observed" calculation.
