### ISSUE TITLE
Return wrong language for the Netherlands holidays

### ISSUE THREAD

**Issue by jovana** [vacanza/python-holidays#1453]
I have updated my code to the latest version and it seems the holiday names do not return in it's own language.
Running this code:

```
import datetime
import holidays

for ptr in holidays.NL(datetime.datetime.now().year).items():
    print(ptr)

```

✅ Running the above code using version 0.22 gives (good and expected results):
```
(datetime.date(2023, 1, 1), 'Nieuwjaarsdag')
(datetime.date(2023, 4, 9), 'Eerste paasdag')
(datetime.date(2023, 4, 7), 'Goede Vrijdag')
(datetime.date(2023, 4, 10), 'Tweede paasdag')
(datetime.date(2023, 5, 18), 'Hemelvaart')
(datetime.date(2023, 5, 28), 'Eerste Pinksterdag')
(datetime.date(2023, 5, 29), 'Tweede Pinksterdag')
(datetime.date(2023, 12, 25), 'Eerste Kerstdag')
(datetime.date(2023, 12, 26), 'Tweede Kerstdag')
(datetime.date(2023, 4, 27), 'Koningsdag')
```

🔴 Running the code from version 0.23 (also the same results running 0.32) gives the below wrong result:
```
(datetime.date(2023, 1, 1), "New Year's Day")
(datetime.date(2023, 4, 7), 'Good Friday')
(datetime.date(2023, 4, 9), 'Easter Sunday')
(datetime.date(2023, 4, 10), 'Easter Monday')
(datetime.date(2023, 4, 27), "King's Day")
(datetime.date(2023, 5, 18), 'Ascension Day')
(datetime.date(2023, 5, 28), 'Whit Sunday')
(datetime.date(2023, 5, 29), 'Whit Monday')
(datetime.date(2023, 12, 25), 'Christmas Day')
(datetime.date(2023, 12, 26), 'Second Day of Christmas')
```

So you can see the dates are correct but the labels (naming) are in English instead of Dutch. If this is the new standard, this is fine for me then I will translate myself. Otherwise, I hope you can fix this.

If you need more info, please me know. I will run version 0.22 in the mean time.

Many thanks for this library!

**Comment by arkid15r** [comment]
Hey @jovana 
thanks for the detailed issue description!

The reason for this (unexpected) behavior is that we've localized NL holidays some time ago. There are currently 3 languages supported: nl (default), en_US, and uk.

And it seems you're running it under `en` locale. Please try setting the language explicitly:

```
import datetime
import holidays

for ptr in holidays.NL(datetime.datetime.now().year, language="nl").items():
    print(ptr)
```

If you're a native Dutch language speaker we'd appreciate you taking a look at those labels and let us know if something isn't correct.

Thank you!

**Comment by jovana** [comment]
Hi @arkid15r , Thanks for the quick reply!

Okay, I understand now! I have added the language="nl" option and it gives the correct output. 
Many thanks!

I have looked into the documentation, now I know I can find it. But it would be nice if there is an example in the readthedocs.

**Comment by jovana** [comment]
> Hey @jovana thanks for the detailed issue description!
> 
> The reason for this (unexpected) behavior is that we've localized NL holidays some time ago. There are currently 3 languages supported: nl (default), en_US, and uk.
> 
> And it seems you're running it under `en` locale. Please try setting the language explicitly:
> 
> ```
> import datetime
> import holidays
> 
> for ptr in holidays.NL(datetime.datetime.now().year, language="nl").items():
>     print(ptr)
> ```
> 
> If you're a native Dutch language speaker we'd appreciate you taking a look at those labels and let us know if something isn't correct.
> 
> Thank you!

I have added an update in the documentation, in this pull request. Not sure if it is usefull: https://github.com/vacanza/python-holidays/pull/1456

Thanks for helping and this great lib!
