### ISSUE TITLE
Incomplete list of Chinese holidays

### ISSUE THREAD

**Issue by SimonaNav** [vacanza/python-holidays#1475]
Hello, I'd like to ask you to check list of  _Chinese_ (CN) holidays. Based on my research (see links below) it seems that some of public holidays are missing there, for example 4.-6.10.2023 (week of _National Day_).
https://www.officeholidays.com/countries/china/2023
https://www.china-briefing.com/news/china-public-holiday-2023-schedule/
https://en.wikipedia.org/wiki/Public_holidays_in_China

Could you please have a look?
Thank you in advance!

**Comment by PPsyrius** [comment]
Seems like none of the English version sources pre-2022 are reliable, though the Chinese government appears to have official ones from [2007](https://www.gov.cn/gongbao/content/2007/content_503397.htm) onwards from their website, which I'm working on at the moment - as well as adding both l10n support (Thai/Simplified Chinese/Traditional Chinese) and half-day holiday supports.
