### ISSUE TITLE
Juneteenth is a NYSE holiday only starting from 2022 and not 2021

### ISSUE THREAD

**Issue by roy-themachine** [vacanza/python-holidays#1482]
The NYSE and other markets have recognized Juneteenth only starting 2022, however when running the following code it recognizes 2021 Juneteenth as a NYSE holiday:

```
import holidays
from datetime import date

nyse_holidays = holidays.NYSE()
print(date(2021, 6, 18) in nyse_holidays)
```

Expected Output:
False

Actual Output:
True

**Comment by KJhellico** [comment]
@roy-themachine, thank you for your suggestion! It will be fixed in next release.
