### ISSUE TITLE
Add UK easter holidays

### ISSUE THREAD

**Issue by remipham** [vacanza/python-holidays#1487]
The holidays in UK don't include easter and the summer bank holiday

![image](https://github.com/vacanza/python-holidays/assets/85238630/467c9f0f-ca29-418f-83ef-d9f06d140420)
![image](https://github.com/vacanza/python-holidays/assets/85238630/52ed9b37-df9a-4895-b66f-01eceb95493d)

**Comment by arkid15r** [comment]
Hi @remipham, try checking the UK holidays for `ENG` and `WLS` subdivs, e.g., `holidays.UK(years=2023, subdiv="ENG")`

**Comment by remipham** [comment]
Thanks, got everything I need!
