### ISSUE TITLE
Canada Object is not running _populate_government_holidays

### ISSUE THREAD

**Issue by AntonioVentilii** [vacanza/python-holidays#1494]
When querying Canadian holidays, the method _populate_government_holidays is not called. Probably even other methods from Canada

**Comment by arkid15r** [comment]
Hey @AntonioVentilii,
did you specify you wanted the `GOVERNMENT` category holidays to be included? The default one is `PUBLIC`.
If so, please share some code examples to reproduce the issue.

Thank you!

**Comment by AntonioVentilii** [comment]
Hi @arkid15r ! Tks for the answer!

Actually, I did not specify it, I imagined all of them would appear if I do a generic search. For example, the Reconciliation Day should appear (30th september 2023, obs. 2nd october 2023), but it doesn't.

```
import holidays

ca_holidays = holidays.country_holidays('Canada', observed=True, years=[2023])

print(ca_holidays)
```

**Comment by arkid15r** [comment]
Hey Antonio,

currently CA holidays implementation adds that holiday for either `GOVERNMENT` category or multiple subdivisions that recognize the holiday. The default CA holidays set does not include "National Day for Truth and Reconciliation" related holidays.

This would work, though:

```
holidays.country_holidays('Canada', years=2023, categories=(holidays.GOVERNMENT,))
holidays.country_holidays('Canada', years=2023, subdiv="BC")
```

Please also note we have sort of related discussion here - https://github.com/vacanza/python-holidays/issues/1492

**Comment by AntonioVentilii** [comment]
Understood! Thank you for the answer!

I will close the issue
