### ISSUE TITLE
TypeError: ObservedHolidayBase._add_observed() got an unexpected keyword argument 'before'

### ISSUE THREAD

**Issue by Yossi** [vacanza/python-holidays#1575]
this test code was working fine under 0.27.1 (where the method was still named _add_with_observed()) but now with the latest 0.37 it complains about 'unexpected argument' as in the title.
what is the new way of adding custom holidays so they can only be pushed forward?

```from datetime import date
from holidays.countries import US
from holidays.constants import JAN, JUL

class MyCivilHolidays(US):
    def _populate(self, year):
        super()._populate(year)
        self.pop_named('New Year')
        self.pop_named('Independence')

        self._add_observed(date(year, JAN, 1), "New Year's Day", before=False) # strictly no backtracks to friday
        self._add_observed(date(year, JUL, 4), 'Independence Day', before=False) # if these fall on saturday then they must be pushed to monday

my_holidays = MyCivilHolidays()

date(2024, 1, 1) in my_holidays```

**Comment by KJhellico** [comment]
Yes, code for observed holidays handling has been significantly changed and unified.

If you want to **exactly** implement the behavior of `before=False` parameter, you need code like:

```python
from holidays.countries import US
from holidays.observed_holiday_base import ObservedHolidayBase, SUN_TO_NEXT_MON

class MyCivilHolidays(US):
    def _populate(self, year):
        super()._populate(year)
        self.pop_named("New Year")
        self.pop_named("Independence")

        self._add_observed(self._add_new_years_day("New Year's Day"), rule=SUN_TO_NEXT_MON)
        self._add_observed(self._add_holiday_jul_4("Independence Day"), rule=SUN_TO_NEXT_MON)
```
But when holiday falls on a Saturday, there will be **no observed at all**.

If it should be exactly as comment says, "if these fall on saturday then they must be pushed to monday", then code should be like:

```python
from holidays.countries import US
from holidays.observed_holiday_base import ObservedHolidayBase, SAT_SUN_TO_NEXT_MON

class MyCivilHolidays(US):
    def _populate(self, year):
        super()._populate(year)
        self.pop_named("New Year")
        self.pop_named("Independence")

        self._add_observed(self._add_new_years_day("New Year's Day"), rule=SAT_SUN_TO_NEXT_MON)
        self._add_observed(self._add_holiday_jul_4("Independence Day"), rule=SAT_SUN_TO_NEXT_MON)
```

**Comment by Yossi** [comment]
this works, thanks.

btw, what are those methods _add_new_years_day() and _add_holiday_jul_4()?
if i wanted to add ninja turtle day is there a special method for that? or can i just name these things whatever on the fly?

**Comment by arkid15r** [comment]
No, those are predefined methods. However, their nature differs a bit. While `_add_new_years_day()` is part of [international holidays group](https://github.com/vacanza/python-holidays/blob/beta/holidays/groups/international.py#L114) the `_add_holiday_jul_4()` is a syntactic sugar method handled by `HolidayBase::__getattr__()` [logic](https://github.com/vacanza/python-holidays/blob/beta/holidays/holiday_base.py#L398) -- you can use `_add_holiday_<3_letter_month_name>_<day_number>()` for adding custom holidays.

**Comment by Yossi** [comment]
but `self._add_holiday_jul_13("Ninja Turtle Day")` and `self[date(year, 7, 13)] = "Ninja Turtle Day"` still do the same thing, yes? or is the latter expected to be deprecated in the future?

**Comment by arkid15r** [comment]
Right, both examples result in the same holidays object state as `HolidayBase` is a dict based object. I don't think the `__setitem__` functionality is going to be deprecated so you can continue using it directly (`self[date(year, 7, 13)] = "Ninja Turtle Day"`).

**Comment by Yossi** [comment]
ok, thank you very much for this useful library
