### ISSUE TITLE
NYSE holidays incorrectly includes new years eve (2021/12/31) when new years day (2022/01/01) falls on Saturday

### ISSUE THREAD

**Issue by ryanlardinois** [vacanza/python-holidays#1583]
The NYSE 2021 holiday calendar lists new years eve (2021/12/31) as a holiday for new years day observed (2022/01/01) as the latter falls on a Saturday.  However, per [NYSE Rule 7.2](https://www.nyse.com/publicdocs/nyse/regulation/nyse/NYSE_Rules.pdf):

`The Exchange will not be open for business on New Year's Day, Martin Luther King Jr. Day, Presidents' Day, Good Friday, Memorial Day, Independence Day, Labor Day, Thanksgiving Day and Christmas Day. When a holiday observed by the Exchange falls on a Saturday, the Exchange will not be open for business on the preceding Friday and when any holiday observed by the Exchange falls on a Sunday, the Exchange will not be open for business on the succeeding Monday, unless unusual business conditions exist, such as the ending of a monthly or yearly accounting period. Adopted: December 30, 2015 (NYSE-2015-67)`

Because 2021/12/31 is the end of the yearly accounting period, new years day is not observed on that date and should not be included as a holiday for the NYSE calendar. 

See also 

https://capital.com/no-new-year-s-holiday-for-wall-street#:~:text=Rule%207.2%20was%20adopted%20in,an%20exception%20to%20the%20rule.

https://www.nasdaqtrader.com/content/technicalsupport/2021tradingcalendar.pdf

https://www.businesswire.com/news/home/20181204005629/en/NYSE-Group-Announces-2019-2020-and-2021-Holiday-and-Early-Closings-Calendar

**Comment by KJhellico** [comment]
@ryanlardinois, thank you for your suggestion! It seems that Friday, December 31, was not a holiday even before 2015 (Rule 7.2 adoption), according to Rule 51. So I think it would be right to remove holiday shift to December 31 completely. It will be fixed in next release.

**Comment by ryanlardinois** [comment]
cheers! Thanks very much.
