### ISSUE TITLE
Regression in holidays in the Netherlands

### ISSUE THREAD

**Issue by harmbuisman** [vacanza/python-holidays#1590]
I noticed the change Update Netherlands holidays: add holiday categories #1552 broke my unit tests as it no longer considers Liberation day as a holiday on the 5yr interval even though it is a holiday for most people in the Netherlands every 5 years.

On Liberation day (Bevrijdingsdag) the majority of employees have a day off every 5 years (2005, 2010, 2015, etc.). This was the previous behaviour which worked as expected.

Now the 5-year rule of Liberation day is combined with Good Friday in the OPTIONAL category. This equates the status of Liberation day with Good Friday, but this is not logical. Good Fridays is more similar to Liberation Day on the non 5yr-years as those are still a bank holiday but fewer people have a guaranteed holiday than in the 5-yr years. There is no option to add the non-5yr holidays it seems.

The behaviour I would expect is:
- PUBLIC includes 5yr Liberation days
- OPTIONAL includes Good Friday and the non-5yr liberation days

**Comment by arkid15r** [comment]
Hi @harmbuisman and thanks for bringing this up!
I understand your concern about the breaking change introduced in #1552 . Sorry about that.

I found a couple of .nl resources mentioning "Liberation day":
  - https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands
  - https://business.gov.nl/regulation/holiday-entitlement/#art:liberation-day-5-may

@KJhellico, should this be revisited based on the report and the resources informaion I've just mentioned?

Thank you!

**Comment by KJhellico** [comment]
Yes, it seems that information about Liberation Day in [Wiki](https://nl.wikipedia.org/wiki/Feestdagen_in_Nederland#Nationale_feestdagen) is not entirely correct: 

> 5 mei is sinds 1990 aangewezen als jaarlijkse nationale feestdag. Hiermee kwam een einde aan de situatie dat 5 mei alleen eens in de vijf jaar een nationale feestdag was.

@harmbuisman, thank you for this info, and sorry for inconvenience caused by these changes. I agree with this position:

> PUBLIC includes 5yr Liberation days
> OPTIONAL includes Good Friday and the non-5yr liberation days

but can you say whether there were any changes in 1990?

**Comment by harmbuisman** [comment]
Hi, thanks for considering the changes. I was a kid in those days, but from what I understand is that. 

- Since 1990, Liberation Day has been a bank holiday every year during which people in some sectors are free (e.g., government), and every 5 years, most sectors have a holiday (as most labor agreements have this in).  (**1990**, 1991, 1992, 1993, 1994, **1995**, 1996, ... etc.),
- Before 1990, Liberation Day was a bank holiday every 5 years (so only **1950**, .. **1985**, **1990**).
