### ISSUE TITLE
Update 2024 Chinese holiday

### ISSUE THREAD

**Issue by peter-ni-noob** [vacanza/python-holidays#1601]
I am Chinese, and Chinese holidy is various from other years,and the holidays of 2024 is published by Chinese government,ref:https://www.gov.cn/yaowen/liebiao/202310/content_6911540.htm。
I want to update this information as my first issue good issue,Can I do this?

**Comment by arkid15r** [comment]
Hi @peter-ni-noob , 
it you feel it's something you can do -- go ahead. Our community welcomes all contributions and ready to help in case you have questions or face issues during the process.

It's great to have another open source contributor interested in Python Holidays!
