### ISSUE TITLE
[US] `Christmas Day (Observed) (Observed)` for some US states/territories

### ISSUE THREAD

**Issue by PPsyrius** [vacanza/python-holidays#1606]
I found this by chance while running `make snapshot` update for Papua New Guinea and Taiwan.
![image](https://github.com/vacanza/python-holidays/assets/19505219/01c89d2a-bce2-469b-8818-6d8a7bd9d04b)

Here's the list of affected states/territories:
- `US_AS` \ `AS`: American Samoa
- `US_KS`: Kansas
- `US_MI`: Michigan
- `US_NC`: North Carolina
- `US_TX`: Texas
- `US_WI`: Wisconsin

For `GU`: Guam, they seem to be missing out on Christmas Day and New Year's Day altogether for some reason, [even if their government does indicate that they should be observed](https://web.archive.org/web/20231006232937/https://www.guamtax.com/help/holidays.html).
![image](https://github.com/vacanza/python-holidays/assets/19505219/595e35df-d307-47f1-ad7e-9a3160a46899)

**Comment by KJhellico** [comment]
@PPsyrius , thanks you for catching this! I've fixed Guam and looking into US.
