### ISSUE TITLE
SyntaxError: invalid escape sequence '\_' with Python 3.11

### ISSUE THREAD

**Issue by phillipuniverse** [vacanza/python-holidays#1612]
Running Python 3.11.4 from a Dockerfile (`python:3.11.4-alpine`). When loading the library, I get this:

```
 app/facilities/holidays/datastructures/standard_holiday_calendar.py:4: in <module>
     from holidays.countries import united_states
  /opt/pysetup/.venv/lib/python3.11/site-packages/holidays/countries/__init__.py:83: in <module>
      from .kazakhstan import Kazakhstan, KZ, KAZ
  E     File "/opt/pysetup/.venv/lib/python3.11/site-packages/holidays/countries/kazakhstan.py", line 18
  E       """
  E       ^^^
  E   SyntaxError: invalid escape sequence '\_'
  make: *** [Makefile:11: test] Error 4
 2
```

Looks like the problematic code was added at https://github.com/vacanza/python-holidays/commit/aa780570ea88fc28a6ac1c0e012cebe60b38b233#diff-3835a4c66a509f1de886fe22c21ea9c22d7e83d49203fdb4dfc448ec56527549R23

the linter also gave a violation here W605 which was ignored explicitly with `# noqa: W605, not sure why

**Comment by arkid15r** [comment]
Thanks for reporting this, it's fixed in https://github.com/vacanza/python-holidays/pull/1619
