### ISSUE TITLE
2023-12-30/31 is holiday in China. However, this library reports false result. It may be a bug. 

### ISSUE THREAD

**Issue by GoForit-007** [vacanza/python-holidays#1638]
2023-12-30/31 is holiday in China. However, this library reports false result. It may be a bug. The corresponding codes are as follows:

`from datetime import date
import holidays

cn_holidays = holidays.China()

check_date = date(2023, 12, 30)  

if check_date in cn_holidays:
    print(f"{check_date} is a holiday in China: {cn_holidays.get(check_date)}")
else:
    print(f"{check_date} is not a holiday in China.")`

**Comment by KJhellico** [comment]
Dec 30 and 31 is Saturday and Sunday, they are non-working days, just like regular weekends. Do you mean that they have some kind of special holiday status?

**Comment by arkid15r** [comment]
I couldn't find any confirmation of 2023-12-30 being a holiday in China. Please reopen with a link to a source attached.

Thank you
