### ISSUE TITLE
holiday in Brazil

### ISSUE THREAD

**Issue by tsaraujo96** [vacanza/python-holidays#1640]
As of version 0.32, several Brazilian holidays from 2024 have disappeared.

Below is the list between the two versions:

### v0.32

(datetime.date(2024, 1, 1), 'Confraternização Universal')
(datetime.date(2024, 2, 12), 'Carnaval')
(datetime.date(2024, 2, 13), 'Carnaval')
(datetime.date(2024, 2, 14), 'Início da Quaresma')
(datetime.date(2024, 3, 29), 'Sexta-feira Santa')
(datetime.date(2024, 4, 21), 'Tiradentes')
(datetime.date(2024, 5, 1), 'Dia do Trabalhador')
(datetime.date(2024, 5, 30), 'Corpus Christi')
(datetime.date(2024, 9, 7), 'Independência do Brasil')
(datetime.date(2024, 10, 12), 'Nossa Senhora Aparecida')
(datetime.date(2024, 10, 28), 'Dia do Servidor Público')
(datetime.date(2024, 11, 2), 'Finados')
(datetime.date(2024, 11, 15), 'Proclamação da República')
(datetime.date(2024, 12, 24), 'Véspera de Natal')
(datetime.date(2024, 12, 25), 'Natal')
(datetime.date(2024, 12, 31), 'Véspera de Ano-Novo')

### v0.33 

(datetime.date(2024, 1, 1), 'Confraternização Universal)
(datetime.date(2024, 3, 29), 'Sexta-feira Santa')
(datetime.date(2024, 4, 21), 'Tiradentes')
(datetime.date(2024, 5, 1), 'Dia do Trabalhador')
(datetime.date(2024, 9, 7), 'Independência do Brasil')
(datetime.date(2024, 10, 12), 'Nossa Senhora Aparecida')
(datetime.date(2024, 11, 2), 'Finados')
(datetime.date(2024, 11, 15), 'Proclamação da República')
(datetime.date(2024, 12, 25), 'Natal')

**Comment by arkid15r** [comment]
There is a separate category for optional BR holidays. Just [pass all categories you need](https://python-holidays.readthedocs.io/en/latest/examples.html#holiday-categories-support) on initialization.
