### ISSUE TITLE
Additional Holidays 

### ISSUE THREAD

**Issue by guarddog13** [vacanza/python-holidays#1643]
Valentine's Day (02/14), St. Patrick's Day (03/17), Halloween (10/31) and Election Day (First Tues every 4 years ((this year is 11/05)) ). Could you please add these to the US Holiday Calendar?

**Comment by PPsyrius** [comment]
Thanks for the correction, I'll get a PR to get this fixed ASAP

**Comment by PPsyrius** [comment]
@KJhellico While the first 3 of the list above aren't official holidays for the US, which category would be the most appropriate here? `WORKDAY`, `OPTIONAL`, or some new ones altogether?

**Comment by KJhellico** [comment]
I think, if such holidays are to be added, there should be a new category for them (UNOFFICIAL or something like that).

**Comment by arkid15r** [comment]
> @KJhellico While the first 3 of the list above aren't official holidays for the US, which category would be the most appropriate here? `WORKDAY`, `OPTIONAL`, or some new ones altogether?

The category support was started as ad-hoc feature and has been improved recently. I think it still needs some more attention in terms of standardized across entities and proper documentation. 
`UNOFFICIAL` / `NON_PUBLIC` would do it for now.

**Comment by PPsyrius** [comment]
I'll use `NON_PUBLIC` for this case then 👍
