### ISSUE TITLE
Some public holidays missing for some countries

### ISSUE THREAD

**Issue by nick2202** [vacanza/python-holidays#1646]
I scraped holidays for some countries:
['AT', 'BE', 'CZ', 'DE', 'ES', 'FR', 'GB', 'HU', 'IE', 'IT', 'LI', 'LT', 'LV', 'NL', 'PL', 'RO'] 
off a website:
[officeholidays.com](https://www.officeholidays.com/)
and compared some of them with the ones in the library, there are quite a few differences. For most (but definitely not all!) of them, I think the scraped data is correct (yours in "self", the scraped ones in "other"):
[difference_holidays.xlsx](https://github.com/vacanza/python-holidays/files/13987544/difference_holidays.xlsx)

**Comment by KJhellico** [comment]
@nick2202, thank you for bringing up this issue.

> For most (but definitely not all!) of them, I think the scraped data is correct

Can you give a few examples?

**Comment by nick2202** [comment]
## library incorrect
### Spain:
- 2020-11-01: All Saints Day
- 2020-12-06: Constitution Day
- etc.
https://en.wikipedia.org/wiki/Public_holidays_in_Spain

### UK/GB:
- 2020-04-13, 2021-04-05, 2022-04-18 etc.: Easter Monday
- 2022-08-29 etc.: Summer Bank Holiday

I suppose there are quite a few more examples, in the other file in my second comment there a few regional holidays listed as public ones for BA for example.

## library correct
### Poland
- 2021-01-06: Epiphany
https://en.wikipedia.org/wiki/Public_holidays_in_Poland

**Comment by KJhellico** [comment]
> ### Spain:
> * 2020-11-01: All Saints Day
> * 2020-12-06: Constitution Day
> * etc.
>   https://en.wikipedia.org/wiki/Public_holidays_in_Spain

[Official source for 2020](https://www.boe.es/buscar/doc.php?id=BOE-A-2019-14552).

> 
> ### UK/GB:
> * 2020-04-13, 2021-04-05, 2022-04-18 etc.: Easter Monday
> * 2022-08-29 etc.: Summer Bank Holiday
>   https://www.gov.uk/bank-holidays

These holidays are relevant only for England, Wales and Northern Ireland, not the entire United Kingdom. They are available in Python Holidays for relevant subdivisions, e.g. `UnitedKingdom(subdiv="ENG")`.

**Comment by KJhellico** [comment]
> I suppose there are quite a few more examples, in the other file in my second comment there a few regional holidays listed as public ones for BA for example.

Yes, perhaps it's worth revisiting holidays of all subdivisions. But I see, for example, that Officeholidays lists Orthodox Christmas as local holiday only for Republika Srpska, although according to official sources, it is also holiday in [Federation of Bosnia and Herzegovina](https://www.paragraf.ba/neradni-dani-fbih.html) and [Brčko District](https://www.paragraf.ba/neradni-dani-brcko.html).

**Comment by nick2202** [comment]
Okay, I see, quite a few intricacies I was not aware of.
Thanks for taking the time to answer, actually not that surprising that your dates are more correct :D

One more try, what about?:
CH:
- 2024-05-19: marked as holiday (maybe supposed to be 2024-05-20 Whit Monday?)

**Comment by KJhellico** [comment]
> One more try, what about?:
> CH:
> 
> * 2024-05-19: marked as holiday (maybe supposed to be 2024-05-20 Whit Monday?)

Yes, Switzerland needs to be seriously revised.  I already see that we have at least Easter Sunday and Whit Sunday, which are not listed as a holidays, and there are many more… Thank you for this catch! 👍

**Comment by PPsyrius** [comment]
@nick2202 That's indeed the case for the newer added/updated countries, i.e. see [China (`CN`)](https://github.com/vacanza/python-holidays/blob/beta/holidays/countries/china.py) and [South Korea (`KR`)](https://github.com/vacanza/python-holidays/blob/beta/holidays/countries/south_korea.py). I usually start with the latest holiday act available for that particular administration, then backtrack from there and, if available, all the exceptions/one-off holidays.

**Comment by PPsyrius** [comment]
## South Korea:
- 2024-04-10 is the provisional __National Assembly Election Day__ https://www.nec.go.kr/site/eng/02/10203000000002020070611.jsp
- 2024-05-23 is the __Alternative holiday for Children's Day__ https://namu.wiki/w/대체%20휴일%20제도#s-5.2.3

## China: 
- 2024: see https://www.gov.cn/zhengce/content/202310/content_6911527.htm

## Japan:
- 2024: see __Japanese Cabinet Office's data__ https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv 
- 2025-01-08: I'm pretty sure both https://www.officeholidays.com/countries/japan/2025 and https://www.timeanddate.com/calendar/?year=2025&country=26 has already updated their data on __Coming of Age Day__ to Jan 13

**Comment by arkid15r** [comment]
@nick2202 thank you for pointing out to the discrepancies. Normally we address them on a per-entity basis. And it seems Switzerland holidays have already been updated in #1648

Could you create a separate issue for each country if there anything that needs to be fixed from your perspective?

Thank you!

**Comment by nick2202** [comment]
Okay, I think I found a few more and will just comment here for now:

- IE: 2024-03-18 should not be a holiday as you do get compensation for a holiday on the weekend but it is not automatically the following Monday (https://www.citizensinformation.ie/en/employment/employment-rights-and-conditions/leave-and-holidays/public-holidays/)
- NL: 2024-03-29 Good Friday is missing, 2024-05-05 Liberation Day is missing (https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands)
- SE is completely bonkers with like 40 public holidays in 2024

**Comment by arkid15r** [comment]
Thanks a lot, @nick2202!
I've created the per-country tickets to address the reported issues.

The reports like this one are really important for keeping the library contents up to date. If you find more cases, please let us know.
