### ISSUE TITLE
Jersey

### ISSUE THREAD

**Issue by jjanderson** [vacanza/python-holidays#1647]
Hello,

Would it be possible to add Jersey as a country to Holidays please?

Many thanks

**Comment by PPsyrius** [comment]
@jjanderson I assume these two are usable sources, right?

https://www.jerseylaw.je/laws/current/Pages/15.560.aspx (Original 1951 Law)
https://www.jerseylaw.je/laws/current/Pages/15.560.20.aspx (Current 2010 Act)

**Comment by jjanderson** [comment]
oh wow! Thanks for such a quick response. Yes those look good. Thanks very much

**Comment by arkid15r** [comment]
> @jjanderson I assume these two are usable sources, right?
> 
> https://www.jerseylaw.je/laws/current/Pages/15.560.aspx (Original 1951 Law) https://www.jerseylaw.je/laws/current/Pages/15.560.20.aspx (Current 2010 Act)

Hey @PPsyrius, does it mean you're going to take care of this one?

**Comment by PPsyrius** [comment]
> Hey @PPsyrius, does it mean you're going to take care of this one?

Yes, I have a PR for this being worked on at the moment
