### ISSUE TITLE
Verify NL holiday calendar

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1653]
2024-03-29 Good Friday is missing, 2024-05-05 Liberation Day is missing (https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands)

_Originally posted by @nick2202 in https://github.com/vacanza/python-holidays/issues/1646#issuecomment-1903926225_

**Comment by KJhellico** [comment]
Now in PH both of these holidays belong to OPTIONAL category - according to [Dutch Wiki](https://nl.wikipedia.org/wiki/Feestdagen_in_Nederland#Algemeen_erkende_feestdagen) and info from #1590.
@nick2202, if you have other info, feel free to comment.

**Comment by nick2202** [comment]
I have looked here: https://wetten.overheid.nl/BWBR0002448/2010-10-10#:~:text=236-,1,is%20equated%20with%20the%20days%20referred%20to%20in%20the%20previous%20paragraph.,-3
This does mention May 5 and Good Friday in the same breath as other public holidays (I do not speak Dutch so this is only the translation).
But I guess I would trust the apparently Dutch person commenting in [#1590](https://github.com/vacanza/python-holidays/issues/1590) more.

**Comment by arkid15r** [comment]
All right, let's keep them optional with no changes at this time.
