### ISSUE TITLE
Fix README links targets

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1677]
Some of the README.rst's `Contributions` and `License` section links looks right on Github but result in 404 on PYPI and RTD platforms. We need to fix it so links would work right everywhere.

**Comment by nwithan8** [comment]
Working fine for me from PyPi: https://pypi.org/project/holidays/

They're absolute URLs, so shouldn't be a problem.

**Comment by arkid15r** [comment]
That's right, the issue has been resolved in https://github.com/vacanza/python-holidays/pull/1745

Thanks for verifying this!
