### ISSUE TITLE
Add Easter Sunday to AU-SA public holiday list

### ISSUE THREAD

**Issue by bbayu123** [vacanza/python-holidays#1725]
According to the South Australian _Public Holidays Act 2023_ - which has gone into effect since 1st January 2024, replacing the _Holidays Act 1910_ - Easter Sunday is observed as a public holiday.

Easter Sunday needs to be added to the AU-SA holiday list starting from 2024.

References:
1. Public holidays (SafeWork SA), <https://www.safework.sa.gov.au/resources/public-holidays>
2. Public Holidays Act 2023, <https://www.legislation.sa.gov.au/lz?path=%2FC%2FA%2FPublic%20Holidays%20Act%202023>

**Comment by KJhellico** [comment]
I'm working on a large update for Australia holidays (inspired by #1674). @bbayu123 , thank you for your suggestion, it will be useful.
