### ISSUE TITLE
Any plan to add Statutory Holidays Category to Hong Kong?

### ISSUE THREAD

**Issue by bbayu123** [vacanza/python-holidays#1726]
In Hong Kong, there are 2 lists of holidays that companies _can_ observe:
- Statutory Holidays (法定假日) defined by the **Section 39** of Cap. 57 Employment Ordinance of the Hong Kong Legislation (《香港法例》第57章 《僱傭條例》第39條), shorted to 勞工假 in Chinese (URL: <https://www.elegislation.gov.hk/hk/cap57!en-zh-Hant-HK?INDEX_CS=N>)
- General Holidays (Public Holidays) (公眾假期) defined by Cap. 149 General Holidays Ordinance of the Hong Kong Legislation (《香港法例》第149章《公眾假期條例》), also called bank holidays (銀行假) by the general public (URL: <https://www.elegislation.gov.hk/hk/cap149!en-zh-Hant-HK?INDEX_CS=N>)

All Statutory Holidays are General Holidays, but not all General Holidays are Statutory Holidays, until the year 2030 where the two lists align.
* 2017 - 2021: 12 Statutory, 17 General Holidays
* 2022 - 2023: 13 Statutory, 17 General Holidays
* 2024 - 2025: 14 Statutory, 17 General Holidays
* 2026 - 2027: 15 Statutory, 17 General Holidays
* 2028 - 2029: 16 Statutory, 17 General Holidays
* 2030 - Until further change: 17 Statutory, 17 General Holidays

Companies are required to grant holidays to employees on the days listed under Statutory Holidays (or an alternative day under employer-employee agreements), but are not required to grant holidays on the days ONLY listed under General Holidays.

Is there any plan to add a separate category for Statutory Holidays?

**Comment by KJhellico** [comment]
So, Statutory Holidays are mandatory for everyone, "General Holidays"-only holidays are optional? Is that correct, @bbayu123 ?

**Comment by bbayu123** [comment]
That is correct. Statutory Holidays are applicable to all employees employed under the law of Hong Kong, where as holidays that are General but not Statutory are only applicable to banks, educational establishments, public offices and Government departments. However, employers can, at their own discretion, decide to grant employees rest days on General Holidays.

The e-Legislation links that I provided actually provide past legislations dating back to 1997, when British (Hong Kong) became HKSAR. It should help you should you decide to add in dates from older years (for example the General Holiday "the birthday of Her Majesty The Queen" prior to HKSAR Establishment, though the exact date where the legislation changes is not really clear without further research.
