### ISSUE TITLE
[development] `make l10n` command is broken

### ISSUE THREAD

**Issue by PPsyrius** [vacanza/python-holidays#1727]
`make l10n` command has been broken since commit `00482f669fabc10083319d658237ae109a689f35` ( #1724 ).

**Comment by KJhellico** [comment]
I have no problems with this (on Windows). But I always run
```
python scripts/l10n/generate_po_files.py
```
because if I try to run script without `python`, it doesn't see installed external packages in my environment. But it was always like that, and I got used to it. :)
BTW, do you have our new `lingva` package installed?

**Comment by PPsyrius** [comment]
> > `make l10n` command has been broken since commit `00482f669fabc10083319d658237ae109a689f35` ( #1724 ).
> 
> What's your `scripts/l10n/generate_po_files.py` run output?

For context, I usually ran `make l10n` and `make snapshot` on WIndows' WSL mode (Ubuntu 22.04), here's the result I got for `make l10n`
```bash
ppsyrius@[redacted]:/mnt/d/[redacted]/python-holidays$ make l10n

scripts/l10n/generate_po_files.py >/dev/null 2>&1
make: *** [Makefile:35: l10n] Error 1
```

**Comment by arkid15r** [comment]
Try `make setup` first. If that doesn't help, run `scripts/l10n/generate_po_files.py` (without stdout/stderr redirect) and paste the error here.

**Comment by arkid15r** [comment]
@PPsyrius have you resolved this?

**Comment by PPsyrius** [comment]
@arkid15r Yes, `make setup` gets `make l10n` work again - thanks for the help :)
