### ISSUE TITLE
Carnaval missing in Brazil after 0.25

### ISSUE THREAD

**Issue by ds-mauri** [vacanza/python-holidays#1780]
Hello!

Noticed that when I run `hhols.country_holidays('BR', years=[2023], observed=True).items()` after the version 0.25 it doesn't bring Carnaval (usually in february) for Brazil. Tried it with the most recent version 0.47.

Should I be calling the function differently?

Thanks!

**Comment by KJhellico** [comment]
Hello, @ds-mauri! Yes, since v0.33 optional holidays in Brazil have been placed in OPTIONAL category. So code should look like:

```python
from holidays.constants import OPTIONAL, PUBLIC
from holidays.utils import country_holidays

# if you need all holidays
br = country_holidays("BR", years=2023, categories=(OPTIONAL, PUBLIC))

# or, if you need OPTIONAL holidays only
br_opt = country_holidays("BR", years=2023, categories=OPTIONAL)


```

**Comment by ds-mauri** [comment]
Amazing! Thanks for the explanation @KJhellico  !

**Comment by avibrazil** [comment]
I was preparing to report a bug about this.
Please consider adding these switches to the most basic documentation that appears everywhere.

**Comment by KJhellico** [comment]
[Changelog](https://holidays.readthedocs.io/en/latest/changelog/#version-033):
> Update Brazil holidays: specify optional holidays ([#1452](https://github.com/vacanza/holidays/pull/1452) by @KJhellico)
