### ISSUE TITLE
South Korea holiday question

### ISSUE THREAD

**Issue by jamjam0109** [vacanza/python-holidays#1789]
Hi friends, long time no see!
I have a question. When I print out South Korea holidays, I don't get "5/1 labor day".

```
import holidays
import pandas as pd

year = 2024
country_code = 'KR'

holidays_in_year = getattr(holidays, country_code)(years=year)
holidays_df = pd.DataFrame(holidays_in_year.items(), columns=['dt', 'holiday']).sort_values('dt', ignore_index=True)
holidays_df
```

![image](https://github.com/vacanza/python-holidays/assets/36263204/9deef42c-edde-4262-9031-a843b8c638cb)

But it's in the [code](https://github.com/vacanza/python-holidays/blob/4efae5107592fc18f29cd9edd17061596fada44c/holidays/countries/south_korea.py#L278). What's wrong?

**Comment by arkid15r** [comment]
Hi @jamjam0109,

It's a `BANK` holiday. Please see the usage examples [here](https://python-holidays.readthedocs.io/en/latest/examples.html#holiday-categories-support).
