### ISSUE TITLE
Election Day public holiday missing from South African public holidays

### ISSUE THREAD

**Issue by tweaver10x** [vacanza/python-holidays#1809]
Yesterday 29 May 2024 was a public holiday in South Africa due to our general elections.  

Official Government Website with list of holidays:  https://www.gov.za/about-sa/public-holidays

Code to test:

sa_holidays = holidays.ZA(years=[current_year])

for holiday in sa_holidays:
    print(holiday)

results:  

2024-01-01
2024-03-21
2024-03-29
2024-04-01
2024-04-27
2024-05-01
2024-06-16
2024-06-17
2024-08-09
2024-09-24
2024-12-16
2024-12-25
2024-12-26

**Comment by KJhellico** [comment]
@tweaver10x, which version of Python Holidays do you use? This holiday has been supported since [v0.47](https://github.com/vacanza/python-holidays/releases/tag/v0.47) (added in #1749).

**Comment by tweaver10x** [comment]
@KJhellico we are using V0.39.  I'll upgrade now, thank you.
