### ISSUE TITLE
Documentation for holidays.US(years=array_of_years) ?

### ISSUE THREAD

**Issue by VikR0001** [vacanza/python-holidays#1846]
I was looking in the docs for how to get the dates of the holidays in a given year. I did not find it. Fortunately chatGPT knew where it was and provided this code, which works:

`us_holidays = holidays.US(years=array_of_years)`

Suggestion: make this more discoverable in the docs.

**Comment by arkid15r** [comment]
@VikR0001 thanks for the suggestion. I think it's worth making the single/multiple year example more prominent. I'll make sure this is added to our [existing examples](https://python-holidays.readthedocs.io/en/latest/examples.html) page (btw, some of them include `years` parameter).
