### ISSUE TITLE
Wrong US holidays for 2009

### ISSUE THREAD

**Issue by d-a-bunin** [vacanza/python-holidays#1963]
### Expected Behavior

Holidays 2009-01-19, 2009-02-16 are present in `holidays.country_holidays(country="US", years=2009)`.

I used resources: [1](https://www.timeanddate.com/holidays/us/2009), [2](https://date.nager.at/PublicHoliday/United-States/2009).

### Actual Behavior

Holidays 2009-01-19, 2009-02-16 aren't present in `holidays.country_holidays(country="US", years=2009)`.

### Steps to Reproduce the Problem

```python
import holidays


def main():
    us_holidays_2009 = holidays.country_holidays(country="US", years=2009)
    print(us_holidays_2009.keys())


if __name__ == "__main__":
    main()
```

### Environment

- OS: macOS Sonoma 14.5
- Python version: 3.10.13
- holidays version: 0.55

### Additional Context

These holidays are present on `holidays==0.20`. I haven't found exactly the version when this change happened.

**Comment by KJhellico** [comment]
@d-a-bunin, I can't reproduce your issue. Your code output:

> dict_keys([datetime.date(2009, 1, 1), datetime.date(2009, 5, 25), datetime.date(2009, 7, 4), datetime.date(2009, 7, 3), datetime.date(2009, 9, 7), datetime.date(2009, 11, 11), datetime.date(2009, 11, 26), datetime.date(2009, 12, 25), datetime.date(2009, 1, 19), datetime.date(2009, 2, 16), datetime.date(2009, 10, 12)])

Both 2009-01-19 and 2009-02-16 are present.

**Comment by d-a-bunin** [comment]
Ok, I'm wrong. I assumed that they should be on first positions, and this assumption was incorrect.
