### ISSUE TITLE
Russian holidays for 2021 are missing some reschedulings

### ISSUE THREAD

**Issue by master0v** [vacanza/python-holidays#432]
Specifically:

For the rational use of weekends and non-working holidays, the Government of the Russian Federation decides:
Reschedule the following weekend in 2021:
from Saturday 2 January to Friday 5 November;
from Sunday 3 January to Friday 31 December;
from Saturday 20 February to Monday 22 February.

Source:
http://www.consultant.ru/law/ref/calendar/proizvodstvennye/2021/

**Comment by bkthomps** [comment]
@master0v is there some logic to this (can it be computed), or do they randomly decide to change them?

**Comment by master0v** [comment]
I don't think this can be computed.  The logic, I believe, is to create continuous holidays without holes in them, so for example Feb 23 is a holiday, so they move the Saturday to Monday, so that people can have 3 continuous days off.  For the other ones, I am not so sure.  Lately the logic of Russian leaders escapes me ;)

**Comment by dr-prodigy** [comment]
This given, we can't implement this change with static logic rules as we normally do. Anyone interested in adding year-specific rules is appreciated, thx.

**Comment by arkid15r** [comment]
The https://github.com/vacanza/python-holidays/pull/1365/ has introduced substituted holidays support recently.
Please consider filing a PR to fix the issue.
