### ISSUE TITLE
Request: Option to get all holidays despite them being on a weekend day

### ISSUE THREAD

**Issue by jahirfiquitiva** [vacanza/python-holidays#565]

**Comment by bkthomps** [comment]
@dr-prodigy this is probably related to Colombia, which is now fixed in 0.15

**Comment by arkid15r** [comment]
Hey @jahirfiquitiva, I'm going to close this now. 
If it's still an issue for you please create a new ticket with detailed explanation of actual and expected behavior.

Thank you
